### PR TITLE
Code improvement3

### PR DESCRIPTION
**Pull request by dingo35**
Code improvements, moving code so less extern global declarations needed, fixed two bugs, commenting unused code, fix compiler warnings.

### CODE REVIEW

**Comment by koen-serneels** [comment]
@dingo35 Thanks for the effort! We went to most of the changes and they seem ok, except could elaborate more on the changes done in #b29bf67 ?

The goal would be to create a auto snapshot build (need to add some Actions stuff first to enable this) from this PR. Are you able to test most of the functionality?

Btw: for the future I would propose to create multiple PR's so we can prioritize them, so like separate code refactorings, bug fixes...This allows to move forward faster with the essential stuff while focusing on this so we keep the risk of breaking stuff as small as possible. Goal is to move quicker with the essential stuff.

**Comment by dingo35** [comment]
Ok guys what is needed to move this forward? You need me to reissue this PR without #b29bf67, and/or without the wifi debugging?

And please note its hard to deliver PR's if we don't accept the wifi debugging PR, since this patch touches all serialprint statements, and I can't code/test/debug without wifi debugging capabilities. So that means that after coding and testing I have to rework every commit to one without the wifi debugging.

Appreciate your work guys, but I think better, faster communication would help this process....

**Comment by koen-serneels** [comment]
Merged in release/v1.4.0 together with the wifi debug
@dingo35 can you test the build resulting from those two pr's? You can find the artifact here: https://github.com/serkri/SmartEVSE-3/actions/runs/2597377462 if you can confirm all is OK we I'll make a new release

**Comment by dingo35** [comment]
@koen-serneels Great work Koen! I checked the sources, all went ok with the merging/git stuff. My own firmware.bin has the same size as yours, there is a diff but this might be due to version differences of platformio ; I am currently running the 1.4.0 generated firmware, all looks great, not sure how long you want me to test :-) .

I added a new PR to update the README.md doc , which IMO should be included in the 1.4.0 release too.

I suggest the PR on the wifi disconnects (the only currently known bug) is for the next (1.5.0 or 1.4.1?) release, but its up to you!

**Pull request merged**
