### PR TITLE
Increased 'safety' temperature thressholds to 70

### PR DESCRIPTION
**Pull request by k-janssens**

### CODE REVIEW

**Comment by k-janssens** [comment]
The source was that it was 40C outside and the evse has no active cooling which resulted in my car stopped charging because evse went higher the 64 degrees.
This "safety" is only applicable for the EVSE module itself and not the 220V wiring or the car or anything else. Rhe ESP modules should be able to withstand much higher temps and there is't much in the module that can generate heat.
Except for the 220 to 12 inverter but that should be able to handle a few degrees higher temp.

fyi 1: my evse didn't went higher then 66C yesterday with this change even after several hours of charging and an ambient temp of 40C.
Without the change my car batt would almost be empty as the evse always stopped as soon 65 was hit but it would never reach the required 55C to start again because it just won't be able to dissipate the heat without any active cooling.

fyi 2: quit sure stegen gives 0 gaurantee:
https://www.stegen.com/nl/ev-producten/66-smart-evse-controller.html

Look at the bottom, he states this as an evaluation kit for testing only to avoid any warranty claims and such

**Comment by dingo35** [comment]
> The source was that it was 40C outside and the evse has no active cooling which resulted in my car stopped charging because evse went higher the 64 degrees. This "safety" is only applicable for the EVSE module itself and not the 220V wiring or the car or anything else. 

Well if one of the components in the SmartEVSE box gets hot, SmartEVSE temp sensor will detect it and turn itself and all the connected components off. So indirectly it will protect also the contactors and the wiring, assumed that is all in the same box as the SmartEVSE.

> Rhe ESP modules should be able to withstand much higher temps and there is't much in the module that can generate heat. Except for the 220 to 12 inverter but that should be able to handle a few degrees higher temp.

Electronic components _only_ wear out from high temperatures (excl. moving parts like contactors). If you can keep the temperature low, electronics will last forever. 

> 
> fyi 1: my evse didn't went higher then 66C yesterday with this change even after several hours of charging and an ambient temp of 40C. Without the change my car batt would almost be empty as the evse always stopped as soon 65 was hit but it would never reach the required 55C to start again because it just won't be able to dissipate the heat without any active cooling.

But what causes that high temperature? Is your contactor running hot? My SmartEVSE has never reached a higher temperature than 52.4C, and even in this hot weather it typically runs at 38C with an incidental peak to 43C. 
BUT my box is not in the full sun, and I have checked temperatures of my contactor at full load to make sure this Chinese stuff really does what it promises.
Perhaps it would help to add a little roof on your SmartEVSE to give it some shade, and check the contactor? 

> 
> fyi 2: quit sure stegen gives 0 gaurantee: https://www.stegen.com/nl/ev-producten/66-smart-evse-controller.html
> 
> Look at the bottom, he states this as an evaluation kit for testing only to avoid any warranty claims and such

You are absolutely right, hadn't seen that stuff but I guess my warranty worries are unnecessary, since there is not any :-) 


Now you can understand that in my situation, even the standard watchdog values are a bit high; if my config reaches 60C or even 65C, something is really wrong. If you don't want to change your hardware (roof, contactor), I can understand that you are satisfied with a somewhat shorter lifespan of your SmartEVSE (since it will not turn off at those incidental high temperatures).
How about we make it a configurable parameter, which is by default set at Stegen's values, and people can increase or decrease if necessary?

**Comment by koen-serneels** [comment]
In short, I do agree that we can make it a toggle or configurable value and/or finding the real "cause" is perhaps a (theoretically) better idea.  

However, in the mean time there is no issue. It's on the main branch only (not 1.4 where we're releasing from) and, to continue this interesting discussion, the temp sensor really gives no extra security. First, it only stops the charging process. The charging process has no influence on the internal temp of the EVSE (I'm talking about the DIN housing itself). So, even if the internal power supply of the EVSE would be overheating, or any other component for that matter, turning off charging will not change anything as it is merely and output of the esp that is turned off. It would be a real watchdog for the EVSE if it would actually turn off the power, but it doesn't do that. Second, if the EVSE DIN housing is put together in a 2nd housing/box together with the contactor, it would start to measure contactor temperature over time. If a sudden increase of temperature occurs, it's probably to late before it gets to the internal DIN housing temp sensor. Also, why would a contactor become hot? The only things I see is a bad connection or pulling to much power over a too small wire section (but in both cases you should probably just buy a charging box in the store and keep your fingers away from this). So to me the sensor is no real added value, it even worse, it gives a false feeling of security. Depending on the setup, your car might already be completely burnt down while the EVSE temp sensor says "all good!" :)

Afaik the J1772 spec only talks about a sensor in the coupler and that is the connector you put in your car. If because of a bad contact, or what

**Comment by fluppie** [comment]
Mine (indoor garage) is already reading 6 degrees higher than the real ambient temp, don't know if it's less accurate or it's because of the heat from esp32 and 230V =>12V power supply.

Looks like ESP32 doesn't care too much about high temps:

> ESP32 is capable of functioning reliably in industrial environments, with an operating temperature ranging from –40°C to +125°C.

afbeelding

**Comment by k-janssens** [comment]
It probably is a bit of a combination.
I have one at my desk for test purposes which is also around 30C after some minutes.
Now I also looked at the specifications of the temp sensor accuracy: ±2°C (max.), 0°C to +70°C
And it is not a calibrated sensor so the measurement can be taken with a bit of salt as wel.

But to keep everybody happy, I added a menu option to configure the max temp safety in 1.3.5 ;)

**Comment by fluppie** [comment]
Maybe for safety reasons not set an absolute number. But make a delta to the default settings. Let's say -5 to +5 degrees if the default 65 deg?

**Pull request merged**
