### PR TITLE
evse.cpp, evse.h: read imported and exported energy from mainsmeter+e…

### PR DESCRIPTION
**Pull request by dingo35**
evse.cpp, evse.h: read imported and exported energy from mainsmeter+evmeter and feed them to the API

For SmartEVSE we have to put our EVmeters (mains, solar panels) on a modbus, so SmartEVSE can read them and adapt the charging current. SmartEVSE is the master of the bus, and only one master is allowed.
A lot of users want to have this information on their domotics systems (like Domoticz, Home Assistant) or other systems, for monitoring, making graphs etc. 

This PR reads the energy information (import and export separated) of the modbus and presents it to the REST API, so other systems can process them.

Has been running stable here for weeks now, so I feel confident putting it out there...

### CODE REVIEW

**Comment by deqw** [comment]
Can you upload your binary? Then I have a look. Thanks.

**Comment by dingo35** [comment]
[firmware.zip](https://github.com/serkri/SmartEVSE-3/files/9076100/firmware.zip)

This version is based on release 1.4.0, on top of it PR's 36-39. Happy testing!

**Comment by dingo35** [comment]
Please note that I have only Eastron meters here, I used all manufacturers documentation but for all other meters the energy output is untested, so please test this extensively on other brands and report back here!

**Comment by deqw** [comment]
Thanks, got it. Using 2 x SDM630 V2 here.

**Comment by dingo35** [comment]
That'll work, 2x SDM72-V2 here:-)

deqw ***@***.***> schreef op 9 juli 2022 10:57:20 CEST:

**Comment by k-janssens** [comment]
@dingo35 @deqw Can you confirm all testing went well? I will merge if all is good

**Comment by dingo35** [comment]
I am running this version for a week now, al the test versions I gave out had this PR in it (because it was easiest for me to compile that version), so ok with me.

**Comment by deqw** [comment]
Go ahead @k-janssens, all fine here. Thanks @dingo35 !

**Pull request merged**
