### PR TITLE
Added availability_topic to the announce message

### PR DESCRIPTION
**Pull request by marcovaneck**
By setting the Birth / Last-Will messages and adding the topic to the Home Assistant discovery messages. Home Assistant will show unavailable when the EVSE is offline.

Note: this doesn't solve the concurrency issue with MQTTclient.publish

### CODE REVIEW

**Comment by dingo35** [comment]
Thanks for your contribution!

**Comment by VelocityMaximus** [comment]
> By setting the Birth / Last-Will messages and adding the topic to the Home Assistant discovery messages. Home Assistant will show unavailable when the EVSE is offline.

The 'last will' works except that there is no timed update to refresh the connected state.
When the MQTT broker is restarted, the 'online' state gets no update and thus being offline.
You can add a timer that updates the 'connected' state or update it when there is another value to publish.

**Comment by dingo35** [comment]
As far as I understand the MQTT broker should retain last will messages, even after restart. Wouldnt make sense to have to have all these clients this logic built in.

Are you sure you configured your broker correctly (especially the persistence part)?

**Comment by VelocityMaximus** [comment]
It is not e retained message. 
A 'last will' message needs to be updated in a manner of time. This  is a watchdog mechanism that needs to be updated within a certain time. If there is no update at all, the MQTT 'last will' revert automatic to offline.
A more in depth explanation is at https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

**Comment by dingo35** [comment]
Your retain flags are all set, so it seems the calls to the library are all ok...

**Comment by dingo35** [comment]
The default keepalive_interval for mosquitto is 60s; if you have a mainsmeter and/or an EVmeter installed through modbus it will update its currents every 2s, so the keepalive should not be a problem.

**Comment by dingo35** [comment]
I still can't reproduce @VelocityMaximus's problem.

If the SmartEVSE is online it says:
SmartEVSE-51446/connected online

If I restart mosquitto, it says:
SmartEVSE-51446/connected offline
...which corresponds to the webinterface, which says MQTT: Disconnected

Then after one or two seconds MQTT reconnects, so webinterface says: MQTT: Connected
...and the broker reports:
SmartEVSE-51446/connected offline

@VelocityMaximus can you please post your http:/smartevse/settings and your /etc/mosquitto contents, as far as they are deviating from the default?

**Pull request merged**
