### PR TITLE
evse.cpp: Further build MQTT capability

### PR DESCRIPTION
**Pull request by hmmbob**
Based on the great work by @arpiecodes, adding MQTT in #159, I've:

- improved the various discovery topics in MQTT
- added the option to set the `mode`, `override_current` and `cp pwm override` directly from Home Assistant 
- added a direct link to the EVSE from the MQTT EVSE device page
- added version information
- added diagnostic sensors (incl uptime)

Works locally, but conflicts with #172 

image

### CODE REVIEW

**Review by dingo35 — CHANGES_REQUESTED** [review]
First of all, love your improvements, making the MQTT interface even easier to use and including select functionality.

Second: we like atomic pull requests; that means no spelling or layout improvements in essential code changes (which your PR certainly is!), but separate these non-essentials from the essential code change; this makes debugging through git-blame a lot easier.
E.g. the joining of lines 2352, 2353 is non-essential, please keep it out of this PR. Same goes for changing the spelling from OFF to Off....

As to your code, I don't like moving towards the supported abbreviations of HA; MQTT is a universal protocol, which people might use to interface to other software than HA; using "device" instead of "dev" , or "model" instead of "mdl", is much clearer, and the cost (a few bytes) is minimal.

Hope you can agree, looking forward to your changes!

**Comment by hmmbob** [comment]
Gotcha, will work on it.

OFF to Off is a functional change btw - otherwise the select didn't work for some reason. Will try to figure out if I can work around this.

**Comment by hmmbob** [comment]
@dingo35 ready for review.

As said, the OFF was a bug fix, but I made it in a different place now. Let me know what you prefer. It needs to be made in either one of these two lines: 2210 or 2447. I prefer 2447 due to the consistency of spelling that way.

**Comment by dingo35** [comment]
-sorry on the OFF/Off issue, now I get the problem. I like to stick to the spelling of StrModem, which is "Smart", "Normal", so lets stick to "Off" like in your original code.
-for version, in the JSON string it is defined like this:
 doc["version"] = String(VERSION);

**Comment by hmmbob** [comment]
OK, think I'm done for now ;-)

image

**Comment by stevoh6** [comment]
I agree with this sentence "I don't like moving towards the supported abbreviations of HA; MQTT is a universal protocol, which people might use to interface to other software than HA; "

I was plannig to provide "autodiscovery" feature for HA separatly from this project, as we have now for API. So If you doesnt wsa to edit yaml files in HA, you will simple intall HACS addoms, which will only push autodiscovery topics to mqtt (something like this) It will be much more cleaner and not tight to one platform, since there is lot of others.

**Comment by hmmbob** [comment]
We could opt to make "home assistant discovery" optional/configurable in the frontend. So, an extra checkbox or something that tells the SmartEVSE to publish the discovery topics to HA.

in that way one could always publish the 'normal' MQTT topics (`MQTTPrefix + topicname`), and only the HA magical discovery topics when the user configured this.

**Comment by stevoh6** [comment]
Yeah, this will be good, I love the idea. But I see two problems (and therefore Im against it :D)
1. resources cost of esp32 ( I wul like to keep space for more useffull stuff)
2. what if other projects woul like to have native support of "autodiscovery" ? It will also cost recources of esp32.

**Comment by arpiecodes** [comment]
The whole power of the current discovery feature is so we do not require any HACS/custom add-ons anymore for it to function. I think it's also very unnecessary to introduce yet another add-on to do basic stuff. Even though it consumes space in the code, the extra resource usage on the device is minimal (as it basically just gets published once). Having said that, the abbreviations would only help marginally here, and I'd prefer the non-abbreviated variants just for clarity.

I also don't think yet another configuration option would make sense here, seen the actual gain (e.g. extra available resources) isn't really worth it imo.

I would however definitely be all for putting the code into separate source files, so it gets less of a hot mess like it is now. But this would be a pretty big undertaking.

Also, I'm of the opinion that certain integrations would deserve deeper integrations than others, if they are popular enough. In this case, I see most people use the MQTT feature with HA (but I could be wrong, hard to say) so for these people it really helps.

Of course, people that do not use HA don't have to use it. This is why I tried to keep the topics and logic generic and non-HA specific. If there even is such a thing. :-)

**Comment by hmmbob** [comment]
Agreeing on wat @arpiecodes says. Zooming in on 1 specific topic:

> I also don't think yet another configuration option would make sense here, seen the actual gain (e.g. extra available resources) isn't really worth it imo.

On the other hand, a user would need to config the MQTT server anyways, just ticking a "Enable Home Assistant Discovery" box would be easy and prevents users that are not using Home Assistant from seeing those `homeassistant/*/config` topics pop up in their broker.

**Comment by dingo35** [comment]
I agree, this is not a real problem. MQTT is a broker service, and a broker should have all the offers it can get, so clients can subscribe to them or not.
If someone has a good proposal for generalizing the topic announcements then lets open a new PR for that, and close this one. 
O it already is :-)

**Pull request merged**
