### PR TITLE
Update evse.cpp

### PR DESCRIPTION
**Pull request by jonasf21**
Add fix for Wifi disconnect issue #27

### CODE REVIEW

**Comment by jonasf21** [comment]
Fix for sporadic disconnects requiring power cycle or using the menu on the EVSE to manually turn wifi off and on again.

**Comment by dingo35** [comment]
Two remarks:
-you talk about check every 120 seconds, but in the code you check every 5 secs. Is that long enough for the firmware to let it try to reconnect itself (autoreconnect=true)?
-perhaps change status == !WL_CONNECTED to status != WL_CONNECTED, a bit cleaner code?

**Comment by jonasf21** [comment]
No, it doesnt check every 120 seconds - thats just the time the EVSE needed (in my tests) to reconnect once its dropped out of the WiFi (artifically). The check is done every 5 seconds. I havent made further analysis why it needs 120 seconds - as my EVSE is installed far appart i cant access TX/RX console to debug. But it works and i am fine with this timeframe.
As for the code: yes thats probably a bit cleaner. Might change it, lets see if there is more feedback on this in general.

**Comment by dingo35** [comment]
You're right, I'll read better next time!

**Comment by koen-serneels** [comment]
Thanks @jonasf21 for the PR. If you don't mind I prefer going with https://github.com/serkri/SmartEVSE-3/pull/32 as soon as we can confirm this works. I'll leave this open until then

**Comment by jonasf21** [comment]
@koen-serneels yes, @dingo35 's fix is working better than mine in terms of reconnect time. Please use his fix and close this pull.

**Pull request closed without merging**
